### ISSUE TITLE
Milestone 6.2 issue pack

### ISSUE THREAD

**Issue by jondot** [jondot/hygen#376]
## Features
* [x] new `init repo` feature allows cloning complete repos both a command and as a new `setup` action (uses `degit` under the hood). E.g. `hygen init repo rakyll/launchpad --to new-folder` and start coding from that.

## Updates
* [x] Refactoring ESM/TS
* [x] Modernize libraries
* [x] Upgrade node for standalone
* [x] migrate from travis to Github Actions
* [x] fix metaverse test suite (ran twice)
